return {
 ["content"]={
  ["files"]={
   ["ls-r"]="",
  },
  ["metadata"]={
   ["directories"]=0,
   ["files"]=1,
   ["path"]="selfautoparent:texmf-local",
   ["remappings"]=1,
  },
  ["remap"]={
   ["ls-r"]="ls-R",
  },
 },
 ["date"]="2016-06-11",
 ["root"]="selfautoparent:texmf-local",
 ["time"]="23:05:57",
 ["type"]="files",
 ["uuid"]="199beedb-49bd-9b43-d64b-fe9236f1e124",
 ["version"]="1.100",
}